export const SHOW_MODAL_ADD = 'SHOW_MODAL_ADD';
export const HIDE_MODAL_ADD = 'HIDE_MODAL_ADD';
export const SHOW_MODAL_CONGRATULATIONS = 'SHOW_MODAL_CONGRATULATIONS';
export const HIDE_MODAL_CONGRATULATIONS = 'HIDE_MODAL_CONGRATULATIONS';
export const SHOW_MODAL_EDIT = 'SHOW_MODAL_EDIT';
export const HIDE_MODAL_EDIT = 'HIDE_MODAL_EDIT';
export const SHOW_MODAL_DELETE = 'SHOW_MODAL_DELETE';
export const HIDE_MODAL_DELETE = 'HIDE_MODAL_DELETE';
